from app.schemas.products import ProductSummary


# 这里先把商品目录写在代码里，是为了让你把“业务数据结构”和“搜索接口边界”先学清楚。
# 后面如果接数据库、向量库或第三方商品接口，只需要替换数据来源，不需要推翻整个接口设计。
# 所有商品都使用真实存在的品牌和型号，但价格仅为演示参考价，不代表实时电商价格。
PRODUCT_CATALOG: list[ProductSummary] = [
    ProductSummary(
        id="earbuds-sony-wf1000xm5",
        name="Sony WF-1000XM5",
        category="蓝牙耳机",
        brand="Sony",
        price=1599,
        price_note="演示参考价，非实时电商价格",
        summary="旗舰真无线降噪耳机，适合通勤、开会和日常高频佩戴。",
        scenario="通勤 / 办公 / 降噪",
        tags=["旗舰", "降噪", "通勤", "高音质"],
        specs=["主动降噪", "多设备切换", "轻量化机身"],
        official_url="https://electronics.sony.com/audio/headphones/truly-wireless-earbuds/p/wf1000xm5-b",
    ),
    ProductSummary(
        id="earbuds-apple-airpods-pro-2",
        name="Apple AirPods Pro (第 2 代)",
        category="蓝牙耳机",
        brand="Apple",
        price=1899,
        price_note="演示参考价，非实时电商价格",
        summary="苹果生态兼容性优秀，适合 iPhone、iPad、Mac 多设备用户。",
        scenario="通勤 / 苹果生态 / 日常使用",
        tags=["苹果生态", "降噪", "空间音频", "轻便"],
        specs=["主动降噪", "通透模式", "个性化空间音频"],
        official_url="https://www.apple.com/airpods-pro/",
    ),
    ProductSummary(
        id="earbuds-bose-qc-ultra",
        name="Bose QuietComfort Ultra Earbuds",
        category="蓝牙耳机",
        brand="Bose",
        price=2299,
        price_note="演示参考价，非实时电商价格",
        summary="沉浸式空间音频和降噪表现突出，适合重视佩戴体验的人群。",
        scenario="通勤 / 音乐 / 降噪",
        tags=["高端", "降噪", "空间音频", "舒适"],
        specs=["Bose Immersive Audio", "主动降噪", "触控操作"],
        official_url="https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCUE-HEADPHONEIN.html",
    ),
    ProductSummary(
        id="earbuds-soundcore-liberty-4-nc",
        name="soundcore Liberty 4 NC",
        category="蓝牙耳机",
        brand="soundcore",
        price=699,
        price_note="演示参考价，非实时电商价格",
        summary="高性价比降噪耳机，适合预算有限但仍想兼顾通勤和会议。",
        scenario="通勤 / 高性价比 / 日常使用",
        tags=["高性价比", "降噪", "长续航", "通勤"],
        specs=["自适应降噪", "多设备连接", "长续航"],
        official_url="https://us.soundcore.com/products/a3947-liberty-4-nc",
    ),
    ProductSummary(
        id="earbuds-sennheiser-momentum-true-wireless-4",
        name="Sennheiser MOMENTUM True Wireless 4",
        category="蓝牙耳机",
        brand="Sennheiser",
        price=2199,
        price_note="演示参考价，非实时电商价格",
        summary="适合偏爱音质和品牌调音风格的用户，兼顾通勤与音乐欣赏。",
        scenario="音乐 / 通勤 / 高音质",
        tags=["高音质", "旗舰", "降噪", "通勤"],
        specs=["自适应降噪", "aptX Lossless", "多点连接"],
        official_url="https://www.sennheiser-hearing.com/en-US/p/momentum-true-wireless-4/",
    ),
    ProductSummary(
        id="earbuds-samsung-galaxy-buds3-pro",
        name="Samsung Galaxy Buds3 Pro",
        category="蓝牙耳机",
        brand="Samsung",
        price=1499,
        price_note="演示参考价，非实时电商价格",
        summary="更适合三星生态和安卓用户，兼顾日常通勤和语音通话。",
        scenario="通勤 / 安卓生态 / 语音通话",
        tags=["安卓生态", "降噪", "通勤", "通话"],
        specs=["主动降噪", "生态联动", "高保真声音"],
        official_url="https://www.samsung.com/us/mobile-audio/galaxy-buds3-pro/",
    ),
    ProductSummary(
        id="keyboard-keychron-k2-he",
        name="Keychron K2 HE",
        category="机械键盘",
        brand="Keychron",
        price=1199,
        price_note="演示参考价，非实时电商价格",
        summary="磁轴键盘，适合想同时覆盖办公与游戏的人群。",
        scenario="办公 / 游戏 / 桌搭",
        tags=["磁轴", "75 配列", "无线", "客制化"],
        specs=["Hall Effect 磁轴", "QMK 支持", "三模连接"],
        official_url="https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard",
    ),
    ProductSummary(
        id="keyboard-keychron-k8-pro",
        name="Keychron K8 Pro",
        category="机械键盘",
        brand="Keychron",
        price=799,
        price_note="演示参考价，非实时电商价格",
        summary="87 键布局，适合办公、程序员和轻度客制化需求。",
        scenario="办公 / 客制化 / 桌搭",
        tags=["87 配列", "无线", "客制化", "办公"],
        specs=["QMK / VIA", "热插拔", "蓝牙 / 有线"],
        official_url="https://www.keychron.com/products/keychron-k8-pro-qmk-via-wireless-mechanical-keyboard",
    ),
    ProductSummary(
        id="keyboard-logitech-mx-mechanical-mini",
        name="Logitech MX Mechanical Mini",
        category="机械键盘",
        brand="Logitech",
        price=1099,
        price_note="演示参考价，非实时电商价格",
        summary="低矮机械键盘，适合跨设备办公和长期打字场景。",
        scenario="办公 / 多设备协作 / 长时间输入",
        tags=["低矮机械", "办公", "多设备", "紧凑布局"],
        specs=["低矮机械轴", "多设备切换", "白色背光"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-mechanical-mini",
    ),
    ProductSummary(
        id="keyboard-nuphy-air75-v2",
        name="NuPhy Air75 V2",
        category="机械键盘",
        brand="NuPhy",
        price=899,
        price_note="演示参考价，非实时电商价格",
        summary="轻薄三模机械键盘，适合桌搭与移动办公。",
        scenario="办公 / 移动办公 / 桌搭",
        tags=["轻薄", "三模", "75 配列", "桌搭"],
        specs=["低矮轴体", "热插拔", "2.4G / 蓝牙 / 有线"],
        official_url="https://nuphy.com/products/air75-v2",
    ),
    ProductSummary(
        id="keyboard-ducky-one-3-tkl",
        name="Ducky One 3 TKL",
        category="机械键盘",
        brand="Ducky",
        price=899,
        price_note="演示参考价，非实时电商价格",
        summary="经典 TKL 配列，适合重视键帽手感和稳定输入体验的用户。",
        scenario="办公 / 游戏 / 桌面输入",
        tags=["TKL", "热插拔", "键帽手感", "稳定"],
        specs=["TKL 配列", "热插拔", "PBT 键帽"],
        official_url="https://www.duckychannel.com.tw/en/Ducky-One-3-TKL",
    ),
    ProductSummary(
        id="keyboard-iqunix-ez63",
        name="IQUNIX EZ63",
        category="机械键盘",
        brand="IQUNIX",
        price=1299,
        price_note="演示参考价，非实时电商价格",
        summary="紧凑配列磁轴键盘，适合追求桌面空间和游戏响应速度。",
        scenario="游戏 / 桌搭 / 紧凑输入",
        tags=["磁轴", "紧凑", "游戏", "桌搭"],
        specs=["63 键布局", "磁轴", "有线模式"],
        official_url="https://iqunix.com/products/ez63",
    ),
    ProductSummary(
        id="mouse-logitech-mx-master-3s",
        name="Logitech MX Master 3S",
        category="鼠标",
        brand="Logitech",
        price=799,
        price_note="演示参考价，非实时电商价格",
        summary="高端办公鼠标，适合设计、表格、多屏协作和长时间办公。",
        scenario="办公 / 设计 / 多屏协作",
        tags=["办公旗舰", "静音", "人体工学", "多设备"],
        specs=["8K DPI", "静音按键", "MagSpeed 电磁滚轮"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-master-3s",
    ),
    ProductSummary(
        id="mouse-logitech-mx-anywhere-3s",
        name="Logitech MX Anywhere 3S",
        category="鼠标",
        brand="Logitech",
        price=599,
        price_note="演示参考价，非实时电商价格",
        summary="便携办公鼠标，适合经常出差或需要多设备切换的用户。",
        scenario="移动办公 / 差旅 / 多设备协作",
        tags=["便携", "办公", "静音", "多设备"],
        specs=["8K DPI", "玻璃表面追踪", "静音按键"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-anywhere-3s",
    ),
    ProductSummary(
        id="mouse-razer-pro-click-mini",
        name="Razer Pro Click Mini",
        category="鼠标",
        brand="Razer",
        price=499,
        price_note="演示参考价，非实时电商价格",
        summary="小巧便携的办公鼠标，兼顾安静点击和外出携带。",
        scenario="移动办公 / 差旅 / 日常办公",
        tags=["便携", "静音", "办公", "双模"],
        specs=["静音微动", "蓝牙 / 2.4GHz", "小尺寸机身"],
        official_url="https://www.razer.com/productivity/razer-pro-click-mini",
    ),
    ProductSummary(
        id="mouse-logitech-g-pro-x-superlight-2",
        name="Logitech G PRO X SUPERLIGHT 2",
        category="鼠标",
        brand="Logitech G",
        price=999,
        price_note="演示参考价，非实时电商价格",
        summary="超轻电竞鼠标，更适合高频游戏和极致灵敏度需求。",
        scenario="游戏 / 电竞 / 高灵敏操作",
        tags=["电竞", "超轻", "高性能", "无线"],
        specs=["HERO 2 传感器", "LIGHTFORCE 微动", "超轻量化"],
        official_url="https://www.logitechg.com/en-us/products/gaming-mice/pro-x-superlight-2-wireless-mouse.html",
    ),
    ProductSummary(
        id="mouse-razer-basilisk-v3-pro-35k",
        name="Razer Basilisk V3 Pro 35K",
        category="鼠标",
        brand="Razer",
        price=1199,
        price_note="演示参考价，非实时电商价格",
        summary="适合游戏和复杂快捷键操作的高端无线鼠标。",
        scenario="游戏 / 创作 / 高级快捷操作",
        tags=["游戏", "高端", "自定义按键", "无线"],
        specs=["35K 传感器", "HyperScroll 倾斜滚轮", "RGB 灯效"],
        official_url="https://www.razer.com/gaming-mice/razer-basilisk-v3-pro",
    ),
    ProductSummary(
        id="mouse-keychron-m6",
        name="Keychron M6",
        category="鼠标",
        brand="Keychron",
        price=399,
        price_note="演示参考价，非实时电商价格",
        summary="兼顾办公和轻度游戏的高性价比无线鼠标。",
        scenario="办公 / 轻度游戏 / 多设备",
        tags=["高性价比", "轻量", "无线", "办公"],
        specs=["26K 传感器", "2.4G / 蓝牙 / 有线", "人体工学曲线"],
        official_url="https://www.keychron.com/products/keychron-m6-wireless-mouse",
    ),
    ProductSummary(
        id="monitor-dell-u2723qe",
        name="Dell UltraSharp U2723QE",
        category="显示器",
        brand="Dell",
        price=4599,
        price_note="演示参考价，非实时电商价格",
        summary="27 英寸 4K 办公显示器，适合开发、数据分析和轻设计。",
        scenario="办公 / 编程 / 设计",
        tags=["4K", "USB-C", "专业办公", "护眼"],
        specs=["27 英寸 4K", "IPS Black", "USB-C Hub"],
        official_url="https://www.dell.com/en-us/shop/dell-ultrasharp-27-4k-usb-c-hub-monitor-u2723qe/apd/210-bdpf/monitors-monitor-accessories",
    ),
    ProductSummary(
        id="monitor-benq-pd2705u",
        name="BenQ PD2705U",
        category="显示器",
        brand="BenQ",
        price=3899,
        price_note="演示参考价，非实时电商价格",
        summary="面向设计和内容创作的 27 英寸 4K 显示器。",
        scenario="设计 / 修图 / 内容创作",
        tags=["4K", "设计向", "色准", "USB-C"],
        specs=["27 英寸 4K", "HDR", "USB-C"],
        official_url="https://www.benq.com/en-us/monitor/professional/pd2705u.html",
    ),
    ProductSummary(
        id="monitor-asus-pa279crv",
        name="ASUS ProArt PA279CRV",
        category="显示器",
        brand="ASUS",
        price=4199,
        price_note="演示参考价，非实时电商价格",
        summary="适合设计师和视频创作者的 ProArt 系列 4K 显示器。",
        scenario="设计 / 剪辑 / 内容创作",
        tags=["4K", "ProArt", "色准", "创作"],
        specs=["27 英寸 4K", "广色域", "USB-C"],
        official_url="https://www.asus.com/displays-desktops/monitors/proart/proart-display-pa279crv/",
    ),
    ProductSummary(
        id="monitor-lg-27up850n",
        name="LG 27UP850N-W",
        category="显示器",
        brand="LG",
        price=2699,
        price_note="演示参考价，非实时电商价格",
        summary="更偏综合办公和轻创作场景的 27 英寸 4K 显示器。",
        scenario="办公 / 轻创作 / 影音",
        tags=["4K", "USB-C", "综合型", "性价比"],
        specs=["27 英寸 4K", "IPS", "USB-C 供电"],
        official_url="https://www.lg.com/us/monitors/lg-27up850n-w-uhd-monitor",
    ),
    ProductSummary(
        id="monitor-samsung-viewfinity-s8",
        name="Samsung ViewFinity S8 27",
        category="显示器",
        brand="Samsung",
        price=3299,
        price_note="演示参考价，非实时电商价格",
        summary="适合办公室、多文档处理和 4K 桌面工作的商务显示器。",
        scenario="办公 / 多窗口处理 / 商务",
        tags=["4K", "商务", "USB-C", "护眼"],
        specs=["27 英寸 4K", "HDR10", "USB-C"],
        official_url="https://www.samsung.com/us/computing/monitors/high-resolution/viewfinity-s8-27-high-resolution-monitor-ls27b804pxnxgo/",
    ),
    ProductSummary(
        id="monitor-aoc-u27u2d",
        name="AOC U27U2D",
        category="显示器",
        brand="AOC",
        price=2999,
        price_note="演示参考价，非实时电商价格",
        summary="适合设计入门和日常办公的 27 英寸 4K 显示器。",
        scenario="办公 / 设计入门 / 影音",
        tags=["4K", "性价比", "设计入门", "Type-C"],
        specs=["27 英寸 4K", "广色域", "Type-C"],
        official_url="https://aoc.com/us/monitors/pro-line/u27u2d",
    ),
    ProductSummary(
        id="ssd-samsung-t7-shield",
        name="Samsung T7 Shield 2TB",
        category="移动固态硬盘",
        brand="Samsung",
        price=1099,
        price_note="演示参考价，非实时电商价格",
        summary="耐用型移动 SSD，适合摄影外拍和视频素材携带。",
        scenario="摄影 / 视频素材 / 外出办公",
        tags=["移动存储", "耐用", "高速", "2TB"],
        specs=["USB 3.2 Gen 2", "防护设计", "2TB 容量"],
        official_url="https://www.samsung.com/us/computing/memory-storage/portable-solid-state-drives/portable-ssd-t7-shield-usb-3-2-2tb-black-mu-pe2t0s-am/",
    ),
    ProductSummary(
        id="ssd-sandisk-extreme-portable",
        name="SanDisk Extreme Portable SSD 2TB",
        category="移动固态硬盘",
        brand="SanDisk",
        price=999,
        price_note="演示参考价，非实时电商价格",
        summary="便携高速移动 SSD，适合差旅办公和文件传输。",
        scenario="移动办公 / 素材传输 / 差旅",
        tags=["移动存储", "便携", "高速", "2TB"],
        specs=["NVMe SSD", "USB-C", "2TB 容量"],
        official_url="https://shop.sandisk.com/products/ssd/portable-ssds/sandisk-extreme-portable-ssd-usb-3-2",
    ),
    ProductSummary(
        id="ssd-crucial-x9-pro",
        name="Crucial X9 Pro 2TB",
        category="移动固态硬盘",
        brand="Crucial",
        price=899,
        price_note="演示参考价，非实时电商价格",
        summary="高性价比移动 SSD，适合大文件搬运和创作者日常备份。",
        scenario="内容创作 / 办公 / 文件备份",
        tags=["高性价比", "移动存储", "便携", "2TB"],
        specs=["USB 3.2 Gen 2", "2TB 容量", "轻巧机身"],
        official_url="https://www.crucial.com/ssd/x9-pro",
    ),
    ProductSummary(
        id="ssd-lexar-sl500",
        name="Lexar SL500 Portable SSD 2TB",
        category="移动固态硬盘",
        brand="Lexar",
        price=1099,
        price_note="演示参考价，非实时电商价格",
        summary="轻薄化设计，适合摄影、剪辑和移动创作场景。",
        scenario="摄影 / 剪辑 / 内容创作",
        tags=["轻薄", "移动存储", "高速", "2TB"],
        specs=["USB 3.2 Gen 2x2", "2TB 容量", "金属机身"],
        official_url="https://www.lexar.com/product/lexar-sl500-portable-ssd/",
    ),
    ProductSummary(
        id="ssd-kingston-xs1000",
        name="Kingston XS1000 2TB",
        category="移动固态硬盘",
        brand="Kingston",
        price=799,
        price_note="演示参考价，非实时电商价格",
        summary="入门便携型移动 SSD，适合学生和基础办公数据随身携带。",
        scenario="办公 / 学习 / 文件随身携带",
        tags=["入门", "高性价比", "便携", "2TB"],
        specs=["USB 3.2 Gen 2", "轻量机身", "2TB 容量"],
        official_url="https://www.kingston.com/en/ssd/xs1000-external-ssd",
    ),
    ProductSummary(
        id="ssd-wd-black-p40",
        name="WD_BLACK P40 Game Drive SSD 2TB",
        category="移动固态硬盘",
        brand="WD_BLACK",
        price=1299,
        price_note="演示参考价，非实时电商价格",
        summary="更偏游戏和高速加载场景的移动 SSD，也适合大型项目素材缓存。",
        scenario="游戏 / 素材缓存 / 高速传输",
        tags=["游戏", "高速", "RGB", "2TB"],
        specs=["USB 3.2 Gen 2x2", "高速读写", "2TB 容量"],
        official_url="https://www.westerndigital.com/products/portable-drives/wd-black-p40-game-drive-usb-3-2-ssd",
    ),
]
