from app.schemas.products import ProductSummary


# 这份商品目录刻意使用真实存在的品牌和型号，目的是让项目更接近真实电商导购场景。
# 这里的价格是“演示参考价”，不是实时电商价格；后续如果接入数据库或外部接口，
# 可以保留同样的数据结构，只替换数据来源。
PRODUCT_CATALOG: list[ProductSummary] = [
    ProductSummary(
        id="earbuds-sony-wf1000xm5",
        name="Sony WF-1000XM5",
        category="蓝牙耳机",
        brand="Sony",
        price=1599,
        price_note="演示参考价，非实时价格",
        summary="旗舰真无线降噪耳机，适合通勤、会议和重视音质的日常使用场景。",
        scenario="通勤 / 办公 / 降噪",
        tags=["旗舰", "降噪", "通勤", "高音质"],
        specs=["主动降噪", "高解析音频", "多设备切换"],
        official_url="https://electronics.sony.com/audio/headphones/truly-wireless-earbuds/p/wf1000xm5-b",
    ),
    ProductSummary(
        id="earbuds-apple-airpods-pro-2",
        name="Apple AirPods Pro（第二代）",
        category="蓝牙耳机",
        brand="Apple",
        price=1899,
        price_note="演示参考价，非实时价格",
        summary="苹果生态体验优秀，适合 iPhone、iPad、Mac 多设备协作用户。",
        scenario="通勤 / 苹果生态 / 日常使用",
        tags=["苹果生态", "降噪", "空间音频", "轻便"],
        specs=["主动降噪", "通透模式", "个性化空间音频"],
        official_url="https://www.apple.com/airpods-pro/specs/",
    ),
    ProductSummary(
        id="earbuds-bose-qc-ultra",
        name="Bose QuietComfort Ultra Earbuds",
        category="蓝牙耳机",
        brand="Bose",
        price=2299,
        price_note="演示参考价，非实时价格",
        summary="主打沉浸式空间音频和强降噪，适合重视佩戴体验与通勤降噪的人群。",
        scenario="通勤 / 音乐 / 降噪",
        tags=["空间音频", "降噪", "通勤", "高端"],
        specs=["Bose Immersive Audio", "主动降噪", "触控操作"],
        official_url="https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCUE-HEADPHONEIN.html",
    ),
    ProductSummary(
        id="earbuds-soundcore-liberty-4-nc",
        name="soundcore Liberty 4 NC",
        category="蓝牙耳机",
        brand="soundcore",
        price=699,
        price_note="演示参考价，非实时价格",
        summary="高性价比降噪耳机，适合预算有限但又希望兼顾通勤和日常听歌的用户。",
        scenario="通勤 / 高性价比 / 日常使用",
        tags=["高性价比", "降噪", "长续航", "通勤"],
        specs=["自适应降噪", "长续航", "多设备连接"],
        official_url="https://us.soundcore.com/products/a3947-liberty-4-nc",
    ),
    ProductSummary(
        id="keyboard-keychron-k2-he",
        name="Keychron K2 HE",
        category="机械键盘",
        brand="Keychron",
        price=1199,
        price_note="演示参考价，非实时价格",
        summary="磁轴键盘，兼顾办公与游戏，适合想体验可调触发行程的人群。",
        scenario="办公 / 游戏 / 桌搭",
        tags=["磁轴", "75配列", "无线", "客制化"],
        specs=["Hall Effect 磁轴", "2.4GHz / 蓝牙 / 有线", "支持 QMK"],
        official_url="https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard",
    ),
    ProductSummary(
        id="keyboard-keychron-k8-pro",
        name="Keychron K8 Pro",
        category="机械键盘",
        brand="Keychron",
        price=799,
        price_note="演示参考价，非实时价格",
        summary="87 键布局，适合兼顾办公和客制化体验的用户。",
        scenario="办公 / 客制化 / 桌搭",
        tags=["87配列", "无线", "客制化", "办公"],
        specs=["QMK / VIA", "热插拔", "蓝牙 / 有线"],
        official_url="https://www.keychron.com/products/keychron-k8-pro-qmk-via-wireless-mechanical-keyboard",
    ),
    ProductSummary(
        id="keyboard-logitech-mx-mechanical-mini",
        name="Logitech MX Mechanical Mini",
        category="机械键盘",
        brand="Logitech",
        price=1099,
        price_note="演示参考价，非实时价格",
        summary="低矮机械键盘，适合办公和跨设备协作场景，主打输入效率与舒适度。",
        scenario="办公 / 多设备协作",
        tags=["低矮机械", "办公", "多设备", "紧凑布局"],
        specs=["低矮机械轴", "多设备切换", "白色背光"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-mechanical-mini",
    ),
    ProductSummary(
        id="keyboard-nuphy-air75-v2",
        name="NuPhy Air75 V2",
        category="机械键盘",
        brand="NuPhy",
        price=899,
        price_note="演示参考价，非实时价格",
        summary="轻薄三模机械键盘，适合桌面整洁和移动办公场景。",
        scenario="办公 / 移动办公 / 桌搭",
        tags=["轻薄", "三模", "75配列", "桌搭"],
        specs=["低矮轴体", "2.4GHz / 蓝牙 / 有线", "热插拔"],
        official_url="https://nuphy.com/products/air75-v2",
    ),
    ProductSummary(
        id="mouse-logitech-mx-master-3s",
        name="Logitech MX Master 3S",
        category="鼠标",
        brand="Logitech",
        price=799,
        price_note="演示参考价，非实时价格",
        summary="高端办公鼠标，适合长时间办公、设计和多屏协作。",
        scenario="办公 / 设计 / 多屏",
        tags=["办公旗舰", "静音", "人体工学", "多设备"],
        specs=["8K DPI", "静音按键", "MagSpeed 电磁滚轮"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-master-3s",
    ),
    ProductSummary(
        id="mouse-logitech-mx-anywhere-3s",
        name="Logitech MX Anywhere 3S",
        category="鼠标",
        brand="Logitech",
        price=599,
        price_note="演示参考价，非实时价格",
        summary="便携办公鼠标，适合经常带电脑出门、在不同平面上工作的用户。",
        scenario="移动办公 / 差旅",
        tags=["便携", "办公", "静音", "多设备"],
        specs=["8K DPI", "静音按键", "玻璃表面追踪"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-anywhere-3s",
    ),
    ProductSummary(
        id="mouse-razer-pro-click-mini",
        name="Razer Pro Click Mini",
        category="鼠标",
        brand="Razer",
        price=499,
        price_note="演示参考价，非实时价格",
        summary="小巧便携的办公鼠标，兼顾安静点击与便携性。",
        scenario="移动办公 / 差旅 / 日常办公",
        tags=["便携", "静音", "办公", "双模"],
        specs=["静音机械微动", "蓝牙 / 2.4GHz", "便携尺寸"],
        official_url="https://www.razer.com/productivity/razer-pro-click-mini",
    ),
    ProductSummary(
        id="mouse-logitech-g-pro-x-superlight-2",
        name="Logitech G PRO X SUPERLIGHT 2",
        category="鼠标",
        brand="Logitech G",
        price=999,
        price_note="演示参考价，非实时价格",
        summary="超轻电竞鼠标，更适合高频游戏和极致灵敏度需求。",
        scenario="游戏 / 电竞",
        tags=["电竞", "超轻", "高性能", "无线"],
        specs=["LIGHTFORCE 混合微动", "HERO 2 传感器", "超轻量化"],
        official_url="https://www.logitechg.com/en-us/products/gaming-mice/pro-x-superlight-2-wireless-mouse.html",
    ),
    ProductSummary(
        id="monitor-dell-u2723qe",
        name="Dell UltraSharp U2723QE",
        category="显示器",
        brand="Dell",
        price=4599,
        price_note="演示参考价，非实时价格",
        summary="27 英寸 4K 专业办公显示器，适合开发、办公和轻设计场景。",
        scenario="办公 / 编程 / 设计",
        tags=["4K", "USB-C", "专业办公", "护眼"],
        specs=["27 英寸 4K", "IPS Black", "USB-C Hub"],
        official_url="https://www.dell.com/en-us/shop/dell-ultrasharp-27-4k-usb-c-hub-monitor-u2723qe/apd/210-bdpf/monitors-monitor-accessories",
    ),
    ProductSummary(
        id="monitor-benq-pd2705u",
        name="BenQ PD2705U",
        category="显示器",
        brand="BenQ",
        price=3899,
        price_note="演示参考价，非实时价格",
        summary="面向设计和内容创作的 27 英寸 4K 显示器。",
        scenario="设计 / 修图 / 内容创作",
        tags=["4K", "设计向", "色彩准确", "USB-C"],
        specs=["27 英寸 4K", "HDR", "USB-C"],
        official_url="https://www.benq.com/en-us/monitor/professional/pd2705u.html",
    ),
    ProductSummary(
        id="monitor-asus-pa279crv",
        name="ASUS ProArt PA279CRV",
        category="显示器",
        brand="ASUS",
        price=4199,
        price_note="演示参考价，非实时价格",
        summary="ProArt 系列 27 英寸 4K 显示器，适合设计师与内容创作者。",
        scenario="设计 / 剪辑 / 内容创作",
        tags=["4K", "ProArt", "色准", "创作"],
        specs=["27 英寸 4K", "广色域", "USB-C"],
        official_url="https://www.asus.com/displays-desktops/monitors/proart/proart-display-pa279crv/",
    ),
    ProductSummary(
        id="monitor-lg-27up850n",
        name="LG 27UP850N-W",
        category="显示器",
        brand="LG",
        price=2699,
        price_note="演示参考价，非实时价格",
        summary="更偏综合办公和轻创作场景的 27 英寸 4K 显示器。",
        scenario="办公 / 轻创作 / 影音",
        tags=["4K", "USB-C", "综合型", "性价比"],
        specs=["27 英寸 4K", "IPS", "USB-C 供电"],
        official_url="https://www.lg.com/us/monitors/lg-27up850n-w-uhd-monitor",
    ),
    ProductSummary(
        id="ssd-samsung-t7-shield",
        name="Samsung T7 Shield 2TB",
        category="移动固态硬盘",
        brand="Samsung",
        price=1099,
        price_note="演示参考价，非实时价格",
        summary="偏耐用和户外场景的移动固态硬盘，适合摄影、视频素材携带。",
        scenario="摄影 / 视频素材 / 外出办公",
        tags=["移动存储", "耐用", "高速", "2TB"],
        specs=["USB 3.2 Gen 2", "防护设计", "2TB 容量"],
        official_url="https://www.samsung.com/us/computing/memory-storage/portable-solid-state-drives/portable-ssd-t7-shield-usb-3-2-2tb-black-mu-pe2t0s-am/",
    ),
    ProductSummary(
        id="ssd-sandisk-extreme-portable",
        name="SanDisk Extreme Portable SSD 2TB",
        category="移动固态硬盘",
        brand="SanDisk",
        price=999,
        price_note="演示参考价，非实时价格",
        summary="适合经常出差和移动办公的便携 SSD，主打体积小和速度快。",
        scenario="移动办公 / 素材传输 / 差旅",
        tags=["移动存储", "便携", "高速", "2TB"],
        specs=["NVMe SSD", "USB-C", "2TB 容量"],
        official_url="https://shop.sandisk.com/products/ssd/portable-ssds/sandisk-extreme-portable-ssd-usb-3-2",
    ),
    ProductSummary(
        id="ssd-crucial-x9-pro",
        name="Crucial X9 Pro 2TB",
        category="移动固态硬盘",
        brand="Crucial",
        price=899,
        price_note="演示参考价，非实时价格",
        summary="高性价比移动 SSD，适合内容创作者和大文件搬运场景。",
        scenario="内容创作 / 办公 / 素材传输",
        tags=["高性价比", "移动存储", "便携", "2TB"],
        specs=["USB 3.2 Gen 2", "2TB 容量", "轻巧便携"],
        official_url="https://www.crucial.com/ssd/x9-pro",
    ),
    ProductSummary(
        id="ssd-lexar-sl500",
        name="Lexar SL500 Portable SSD 2TB",
        category="移动固态硬盘",
        brand="Lexar",
        price=1099,
        price_note="演示参考价，非实时价格",
        summary="轻薄化移动 SSD，适合摄影、剪辑和内容创作者做高速外接存储。",
        scenario="摄影 / 剪辑 / 内容创作",
        tags=["轻薄", "移动存储", "高速", "2TB"],
        specs=["USB 3.2 Gen 2x2", "2TB 容量", "轻薄金属机身"],
        official_url="https://www.lexar.com/product/lexar-sl500-portable-ssd/",
    ),
]
