from app.schemas.products import ProductSummary


# This seed data intentionally uses real brands and real product models so the demo
# feels closer to a real ecommerce assistant. Prices are reference prices for the demo,
# not real-time quotations. Official URLs are kept so later iterations can explain
# where product facts came from and why the agent should not invent hardware specs.
PRODUCT_CATALOG: list[ProductSummary] = [
    ProductSummary(
        id="earbuds-sony-wf1000xm5",
        name="Sony WF-1000XM5",
        category="蓝牙耳机",
        brand="Sony",
        price=1599,
        price_note="演示参考价，非实时价格",
        summary="旗舰真无线降噪耳机，适合通勤、会议和重视音质的日常使用场景。",
        scenario="通勤 / 办公 / 降噪",
        tags=["旗舰", "降噪", "通勤", "高音质"],
        specs=["主动降噪", "高解析音频", "多设备切换"],
        official_url="https://electronics.sony.com/audio/headphones/truly-wireless-earbuds/p/wf1000xm5-b",
    ),
    ProductSummary(
        id="earbuds-apple-airpods-pro-3",
        name="Apple AirPods Pro 3",
        category="蓝牙耳机",
        brand="Apple",
        price=1999,
        price_note="演示参考价，非实时价格",
        summary="苹果生态体验出色，适合 iPhone 用户做通勤、通话和多设备协作。",
        scenario="通勤 / 苹果生态 / 日常使用",
        tags=["苹果生态", "降噪", "空间音频", "轻便"],
        specs=["主动降噪", "通透模式", "个性化空间音频"],
        official_url="https://www.apple.com/airpods-pro/specs/",
    ),
    ProductSummary(
        id="keyboard-keychron-k2-he",
        name="Keychron K2 HE",
        category="机械键盘",
        brand="Keychron",
        price=1199,
        price_note="演示参考价，非实时价格",
        summary="磁轴键盘，兼顾办公与游戏，适合想体验可调触发行程的人群。",
        scenario="办公 / 游戏 / 桌搭",
        tags=["磁轴", "75配列", "无线", "客制化"],
        specs=["Hall Effect 磁轴", "2.4GHz / 蓝牙 / 有线", "支持 QMK"],
        official_url="https://www.keychron.com/products/keychron-k2-he-wireless-magnetic-switch-keyboard",
    ),
    ProductSummary(
        id="keyboard-logitech-mx-mechanical-mini",
        name="Logitech MX Mechanical Mini",
        category="机械键盘",
        brand="Logitech",
        price=1099,
        price_note="演示参考价，非实时价格",
        summary="低矮机械键盘，适合办公和跨设备协作场景，主打输入手感与效率。",
        scenario="办公 / 多设备协作",
        tags=["低矮机械", "办公", "多设备", "紧凑布局"],
        specs=["低矮机械轴", "多设备切换", "白色背光"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-mechanical-mini",
    ),
    ProductSummary(
        id="mouse-logitech-mx-master-3s",
        name="Logitech MX Master 3S",
        category="鼠标",
        brand="Logitech",
        price=799,
        price_note="演示参考价，非实时价格",
        summary="高端办公鼠标，适合长时间办公、设计和多屏协作。",
        scenario="办公 / 设计 / 多屏",
        tags=["办公旗舰", "静音", "人体工学", "多设备"],
        specs=["8K DPI", "静音按键", "MagSpeed 电磁滚轮"],
        official_url="https://www.logitech.com/en-us/shop/p/mx-master-3s",
    ),
    ProductSummary(
        id="monitor-dell-u2723qe",
        name="Dell UltraSharp U2723QE",
        category="显示器",
        brand="Dell",
        price=4599,
        price_note="演示参考价，非实时价格",
        summary="27 英寸 4K 专业办公显示器，适合开发、办公和轻设计场景。",
        scenario="办公 / 编程 / 设计",
        tags=["4K", "USB-C", "专业办公", "护眼"],
        specs=["27 英寸 4K", "IPS Black", "USB-C Hub"],
        official_url="https://www.dell.com/en-us/shop/dell-ultrasharp-27-4k-usb-c-hub-monitor-u2723qe/apd/210-bdpf/monitors-monitor-accessories",
    ),
]
